module.exports = {
  prodjson: {
    headers: [
      { label: "ID", key: "id" },
      { label: "Tipo", key: "tipo" },
      { label: "Nombre", key: "nombre" },
      { label: "Publicado", key: "publicado" },
      { label: "¿Está destacado?", key: "destacado" },
      { label: "Visibilidad en el catálogo", key: "visibilidad" },
      { label: "Descripción corta", key: "descripcioncorta" },
      { label: "Descripción", key: "descripcion" },
      { label: "Estado del impuesto", key: "estadoimpuesto" },
      { label: "Clase de impuesto", key: "claseimpuesto" },
      { label: "¿En inventario?", key: "eninventario" },
      { label: "¿Permitir reservas de productos agotados?", key: "reservas" },
      { label: "¿Vendido individualmente?", key: "individualmente" },
      { label: "¿Permitir valoraciones de clientes?", key: "valoraciones" },
      { label: "Precio normal", key: "precio" },
      { label: "Categorías", key: "categorias" },
      { label: "Imágenes", key: "imagenes" },
      { label: "Superior", key: "superior" },
      { label: "Nombre del atributo 1", key: "nombreattr1" },
      { label: "Valor(es) del atributo 1", key: "valorattr1" },
      { label: "Atributo visible 1", key: "attrvisible1" },
      { label: "Atributo global 1", key: "attrglobal1" },
      { label: "Atributo por defecto 1", key: "attrdefecto1" },
      { label: "SKU", key: "sku" },
    ],
    dataTemplate: {
      id: 1,
      tipo: "variable",
      nombre: "toallita para bebe",
      publicado: 1,
      destacado: 0,
      visibilidad: "visible",
      descripcioncorta: "",
      descripcion: "",
      estadoimpuesto: "taxable",
      claseimpuesto: "",
      eninventario: "1",
      reservas: 0,
      individualmente: 0,
      valoraciones: 0,
      precio: "",
      categorias: "",
      imagenes: "",
      superior: "",
      nombreattr1: "",
      valorattr1: "",
      attrvisible1: "",
      attrglobal1: "0",
      attrdefecto1: "",
      sku: "",
    },
  },
};
